version: '3'
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: groceryexpress
    ports:
      - "3366:3306"
    networks:
      - mynetwork

  customer:
    image: grocery-express/customer
    restart: always
    hostname: customer
    scale: 1
    ports:
      - "8088:8088"
    networks:
      - mynetwork
    depends_on:
      - mysql

  store:
    image: grocery-express/store
    restart: always
    hostname: store
    scale: 1
#    ports:
    ##      - "8089:8089"
    networks:
      - mynetwork
    depends_on:
      - mysql

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - store
      - customer
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge